basic:
  share_links:
    client: true
    type: list
    default: 'twitter|facebook|email|renren'
    allow_any: false
    choices:
     - twitter
     - facebook
     - email
     - renren
login:
  wechat_qrconnect_client_id444:
    default: ''
  wechat_qrconnect_client_secret:
    default: ''
